alias cp='cp -i'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias helmfile-stage-va='helmfile -e stage-va'
alias k='kubectl -n stage-va'
alias k3='kubectl -n a3-stage-va'
alias kc='kubectl -n common'
alias kd='kubectl -n xcd'
alias kg='kubectl -n guest'
alias kl='kubectl -n eloc'
alias klo='kubectl -n loki'
alias km='kubectl -n monitoring'
alias kmsp='kubectl -n msp4xiq'
alias kn='kubectl -n nvo'
alias kp='kubectl -n stage-va-portal'
alias kw='kubectl -n wips'
alias kws='kubectl -n workspace'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias pscp.pssh='pscp.pssh -O StrictHostKeyChecking=no'
alias psqlconfigdb_1='psql -h aurora-stage-va.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U configuser_1 configdb_1'
alias psqldcsdb='psql -h aurora-stage-va.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U stagedcsuser1 dcs_db'
alias psqlnvodb='psql -h aurora-stage-va.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U nvouser nvo_db'
alias psqlscheduledb='psql -h aurora-stage-va.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U scheduleuser scheduledb'
alias psqlsystemdb='psql -h aurora-stage-va.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U systemuser systemdb'
alias pssh='pssh -O StrictHostKeyChecking=no'
alias python='/usr/bin/python3'
alias rm='rm -i'
alias st='source /root/oss-orchestrator/tools/tools.sh'
alias vi='/bin/vim'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'