alias k='kubectl -n us1-staging'
alias ka='kubectl -n argo'
alias kai='kubectl -n aiexpert'
alias kc='kubectl -n common'
alias kd='kubectl -n xcd'
alias klo='kubectl -n loki'
alias km='kubectl -n monitoring'
alias kmsp='kubectl -n msp4xiq'