alias cp='cp -i'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias flink='kubectl -n stage exec flink-jobmanager-0 -c jobmanager -- flink '
alias flink-cancel='kubectl -n stage exec flink-jobmanager-0 -c jobmanager -- flink cancel '
alias flink-list='kubectl -n stage exec flink-jobmanager-0 -c jobmanager -- flink list '
alias flink-run='kubectl -n stage exec flink-jobmanager-0 -c jobmanager -- flink run '
alias go_mon_wd='f(){ cd /home/jwyang/workspace/github/oss-monitoring/prometheus/deployment/$rdc/; unset -f; }; f'
alias grep='grep --color=auto'
alias helmfile-stage='helmfile -e stage'
alias k='kubectl -n stage'
alias k3='kubectl -n a3-stage'
alias kafka-acls='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-acls.sh --bootstrap-server  default-kafka:9092 '
alias kafka-broker-api-versions='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-broker-api-versions.sh --bootstrap-server  default-kafka:9092 '
alias kafka-configs='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-configs.sh --bootstrap-server  default-kafka:9092 --all  '
alias kafka-configs-describe-topic='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-configs.sh --bootstrap-server  default-kafka:9092 --describe --all --topic '
alias kafka-console-consumer='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-console-consumer.sh --bootstrap-server  default-kafka:9092 '
alias kafka-console-consumer-topic='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-console-consumer.sh --bootstrap-server  default-kafka:9092 --topic '
alias kafka-console-consumer-topic-from-beginning='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-console-consumer.sh --bootstrap-server  default-kafka:9092 --from-beginning --topic '
alias kafka-console-producer='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-console-producer.sh --bootstrap-server  default-kafka:9092 '
alias kafka-consumer-groups='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-consumer-groups.sh --bootstrap-server  default-kafka:9092 '
alias kafka-consumer-perf-test='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-consumer-perf-test.sh '
alias kafka-delegation-tokens='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-delegation-tokens.sh  --bootstrap-server  default-kafka:9092 '
alias kafka-delete-records='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-delete-records.sh --bootstrap-server  default-kafka:9092 '
alias kafka-dump-log='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-dump-log.sh '
alias kafka-log-dirs='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-log-dirs.sh --bootstrap-server  default-kafka:9092 '
alias kafka-mirror-maker='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-mirror-maker.sh '
alias kafka-preferred-replica-election='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-preferred-replica-election.sh --zookeeper  kafka-zookeeper:2181 '
alias kafka-producer-perf-test='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-producer-perf-test.sh '
alias kafka-reassign-partitions='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-reassign-partitions.sh --zookeeper  kafka-zookeeper:2181 '
alias kafka-replica-verification='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-replica-verification.sh '
alias kafka-run-class='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-run-class.sh '
alias kafka-server-start='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-server-start.sh --zookeeper  kafka-zookeeper:2181 '
alias kafka-server-stop='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-server-stop.sh --zookeeper  kafka-zookeeper:2181 '
alias kafka-streams-application-reset='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-streams-application-reset.sh --zookeeper  kafka-zookeeper:2181 '
alias kafka-topics='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-topics.sh --zookeeper  kafka-zookeeper:2181 '
alias kafka-topics-list='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-topics.sh --zookeeper  kafka-zookeeper:2181 --list'
alias kafka-verifiable-consumer='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-verifiable-consumer.sh --bootstrap-server  default-kafka:9092 '
alias kafka-verifiable-producer='kubectl -n stage exec default-kafka-0 -c kafka -- kafka-verifiable-producer.sh --bootstrap-server  default-kafka:9092 '
alias kc='kubectl -n common'
alias kd='kubectl -n xcd'
alias kg='kubectl -n guest'
alias kl='kubectl -n eloc'
alias klo='kubectl -n loki'
alias km='kubectl -n monitoring'
alias kmsp='kubectl -n msp4xiq'
alias kn='kubectl -n nvo'
alias kp='kubectl -n stage-portal'
alias ks='kubectl -n sdwan'
alias kubectla3='kubectl -n a3-stage --kubeconfig ~/.kube/config-a3'
alias kw='kubectl -n wips'
alias kws='kubectl -n workspace'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias pscp.pssh='pscp.pssh -O StrictHostKeyChecking=no'
alias psqlconfigdb_1='psql -h 127.0.0.1 -U configuser_1 configdb_1 -p 5433'
alias psqldcsdb='psql -h aurora-stage.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U stagedcsuser1 dcs_db'
alias psqlelocdb='psql -h aurora-stage-extreme.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U cloudops eloc_db'
alias psqlguestdb='psql -h aurora-stage-extreme.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U postgres cguest_db'
alias psqlnvodb='psql -h aurora-stage.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U nvouser nvo_db'
alias psqlregional_sysmgrdb='psql -h aurora-stage.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U regional_sysmgruser regional_sysmgrdb'
alias psqlscheduledb='psql -h aurora-stage.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U scheduleuser scheduledb'
alias psqlsdwandb='psql -h aurora-stage-sdwan.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U postgres sdwan'
alias psqlsystemdb='psql -h aurora-stage.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U systemuser systemdb'
alias psqlwipsdb='psql -h aurora-stage-extreme.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U postgres wipsdb'
alias psqlxcdlic='psql -h aurora-stage-extreme.cluster-cngszqevwpi5.us-east-1.rds.amazonaws.com -U postgres xcd_licensing_db'
alias pssh='pssh -O StrictHostKeyChecking=no'
alias python='/usr/bin/python3'
alias refresh_mon_conf='f(){ cd /home/jwyang/workspace/github/oss-monitoring/prometheus/deployment/$rdc/ && helm upgrade prometheus -f prometheus-values.yaml xcloudiq/prometheus -n monitoring; unset -f; }; f'
alias resync-flink-job='cd /root/oss-orchestrator/rdc;helmfile -e stage -l layer=flink-job destroy;sleep 10; helmfile -e stage -l layer=flink-job sync'
alias resync-flink-job-detection='cd /root/oss-orchestrator/rdc; helmfile -e stage -l name=alert-detection-flink-job sync'
alias resync-flink-job-email='cd /root/oss-orchestrator/rdc; helmfile -e stage -l name=alert-notification-email-flink-job sync'
alias resync-flink-job-sms='cd /root/oss-orchestrator/rdc;helmfile -e stage -l name=alert-notification-sms-flink-job sync'
alias rm='rm -i'
alias st='source /root/oss-orchestrator/tools/tools.sh'
alias update_mon_git='cd ~/workspace/github/oss-monitoring/ && git pull'
alias vi='/bin/vim'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'