alias cp='cp -i'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias go_mon_wd='f(){ cd /home/jwyang/workspace/github/oss-monitoring/prometheus/deployment/$rdc/; unset -f; }; f'
alias grep='grep --color=auto'
alias helmfile-eu1='helmfile -e eu1'
alias k='kubectl -n eu1'
alias k3='kubectl -n a3-eu1'
alias kc='kubectl -n common'
alias kd='kubectl -n xcd'
alias kg='kubectl -n guest'
alias kl='kubectl -n eloc'
alias klo='kubectl -n loki'
alias km='kubectl -n monitoring'
alias kmsp='kubectl -n msp4xiq'
alias kn='kubectl -n nvo'
alias kp='kubectl -n eu1-portal'
alias kw='kubectl -n wips'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias pscp.pssh='pscp.pssh -O StrictHostKeyChecking=no'
alias psqlaccountdb='psql -h eu1-pg-0.ch3u8doejdmp.eu-central-1.rds.amazonaws.com -U accountuser accountdb'
alias psqlglobal_sysmgrdb='psql -h eu1-pg-0.ch3u8doejdmp.eu-central-1.rds.amazonaws.com -U global_sysmgruser global_sysmgrdb'
alias pssh='pssh -O StrictHostKeyChecking=no'
alias python='/usr/bin/python3'
alias refresh_mon_conf='f(){ cd /home/jwyang/workspace/github/oss-monitoring/prometheus/deployment/$rdc/ && helm upgrade prometheus -f prometheus-values.yaml xcloudiq/prometheus -n monitoring; unset -f; }; f'
alias rm='rm -i'
alias update_mon_git='cd ~/workspace/github/oss-monitoring/ && git pull'
alias vi='/bin/vim'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'