alias cp='cp -i'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias go_mon_wd='f(){ cd /home/jwyang/workspace/github/oss-monitoring/prometheus/deployment/$rdc/; unset -f; }; f'
alias grep='grep --color=auto'
alias helmfile-eu0='helmfile -e eu0'
alias helmfile-portal='helmfile -e portal'
alias k='kubectl -n eu0'
alias k3='kubectl -n a3-eu0'
alias ka='kubectl -n argo'
alias kai='kubectl -n aiexpert'
alias kc='kubectl -n common'
alias kd='kubectl -n xcd'
alias ke='kubectl -n eva'
alias kg='kubectl -n guest'
alias kgc='kubectl -n global-cache'
alias kl='kubectl -n eloc'
alias klo='kubectl -n loki'
alias km='kubectl -n monitoring'
alias kmsp='kubectl -n msp4xiq'
alias kn='kubectl -n nvo'
alias kp='kubectl -n portal'
alias ks='kubectl -n sdwan'
alias kubectl-mon='kubectl -n monitoring'
alias kubectl-portal='kubectl -n portal'
alias kw='kubectl -n wips'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias pscp.pssh='pscp.pssh -O StrictHostKeyChecking=no'
alias psqla3='psql -h aurora-eu0.cluster-c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U cloudops a3'
alias psqlaccountdb='psql -h eu0-pg-0.c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U cloudops accountdb'
alias psqlassetsdb='psql -h eu0-pg-0.c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U prodassetsuser assetsdb'
alias psqlglobal_sysmgrdb='psql -h eu0-pg-0.c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U cloudops global_sysmgrdb'
alias psqlmspdb='psql -h eu0-pg-0.c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U mspuser1 msp_ws_db'
alias psqlmspschedulerdb='psql -h eu0-pg-0.c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U mspuser1 msp_ws_scheduler_db'
alias psqlportaldb='psql -h aurora-eu0.cluster-c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U cloudops portaldb'
alias psqlproductinfodb='psql -h aurora-eu0.cluster-c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U cloudops productinfodb'
alias psqlredirectordb='psql -h aurora-eu0.cluster-c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U cloudops redirectordb'
alias psqlsdwandb='psql -h  aurora-eu0-sdwan.cluster-c1hepewsfuyq.eu-west-1.rds.amazonaws.com  -U cloudops sdwan'
alias psqluzredirectordb='psql -h aurora-eu0.cluster-c1hepewsfuyq.eu-west-1.rds.amazonaws.com -U cloudops uz_redirector_db '
alias pssh='pssh -O StrictHostKeyChecking=no'
alias python='/usr/bin/python3'
alias refresh_mon_conf='f(){ cd /home/jwyang/workspace/github/oss-monitoring/prometheus/deployment/$rdc/ && helm upgrade prometheus -f prometheus-values.yaml xcloudiq/prometheus -n monitoring; unset -f; }; f'
alias rm='rm -i'
alias update_mon_git='cd ~/workspace/github/oss-monitoring/ && git pull'
alias vi='/bin/vim'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'