alias k='kubectl -n cop1r1'
alias k3='kubectl -n a3-cop1r1'
alias kp='kubectl -n cop1r1-portal'
alias kg='kubectl -n guest'
alias kl='kubectl -n eloc'
alias klo='kubectl -n wips'
alias kc='kubectl -n common'
alias kd='kubectl -n xcd'
alias psqlargodb='kubectl -n argo exec -it argo-postgresql-ha-postgresql-0 -c postgresql -- bash -c PGPASSWORD=aerohive psql -h localhost -U postgres'
