alias k='kubectl -n 2degrees'
alias k3='kubectl -n a3'
alias kc='kubectl -n common'
alias kg='kubectl -n guest'
alias kl='kubectl -n eloc'
alias klo='kubectl -n loki'
alias km='kubectl -n monitoring'
alias kw='kubectl -n wips'